server:
  port: 8777
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3306/assignment
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

---
dummy-data:
  enable: true